/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

/**
 *
 * @author ACER
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        // Placeholder untuk Text Field
        namapemesananField.putClientProperty("JTextField.placeholderText", "Nama sesuai KTP");
        nomorhpField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxxx");

        // Mengatur tombol Pesan menjadi tombol default (bisa ditekan pakai Enter)
        getRootPane().setDefaultButton(tombolpesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        namapemesananField = new javax.swing.JTextField();
        nomorhpField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        ekonomiButton = new javax.swing.JRadioButton();
        bagasiCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tombolpesanButton = new javax.swing.JButton();
        modegelapToggle = new javax.swing.JToggleButton();
        bisnisButton = new javax.swing.JRadioButton();
        eksekutifButton = new javax.swing.JRadioButton();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namapemesananField.setText("Nama Pemesanan");
        namapemesananField.addActionListener(this::namapemesananFieldActionPerformed);

        nomorhpField.setText("Nomor HP");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        ekonomiButton.setText("Ekonomi");

        bagasiCheck.setText("Bagasi");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jTextArea1.setText("\n");
        jScrollPane1.setViewportView(jTextArea1);

        tombolpesanButton.setText("Tombol Pesan");
        tombolpesanButton.addActionListener(this::tombolpesanButtonActionPerformed);

        modegelapToggle.setText("Mode Gelap");
        modegelapToggle.addActionListener(this::modegelapToggleActionPerformed);

        bisnisButton.setText("Bisnis");

        eksekutifButton.setText("Eksekutif");

        makanCheck.setText("Makan");

        asuransiCheck.setText("Asuransi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(modegelapToggle)
                .addGap(37, 37, 37)
                .addComponent(tombolpesanButton)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bagasiCheck)
                        .addGap(18, 18, 18)
                        .addComponent(makanCheck)
                        .addGap(18, 18, 18)
                        .addComponent(asuransiCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ekonomiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bisnisButton)
                        .addGap(18, 18, 18)
                        .addComponent(eksekutifButton))
                    .addComponent(namapemesananField)
                    .addComponent(nomorhpField)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(namapemesananField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomorhpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekonomiButton)
                    .addComponent(bisnisButton)
                    .addComponent(eksekutifButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagasiCheck)
                    .addComponent(makanCheck)
                    .addComponent(asuransiCheck))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolpesanButton)
                    .addComponent(modegelapToggle))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namapemesananFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapemesananFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapemesananFieldActionPerformed

    private void tombolpesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolpesanButtonActionPerformed
        String kelas = ekonomiRadio.isSelected() ? "Ekonomi" : bisnisRadio.isSelected() ? "Bisnis" : "Eksekutif";

    List<String> fasilitas = new ArrayList<>();
    if (bagasiCheck.isSelected()) fasilitas.add("Bagasi");
    if (makanCheck.isSelected()) fasilitas.add("Makan");
    if (asuransiCheck.isSelected()) fasilitas.add("Asuransi");

    String pesan = "Nama: " + namapemesananField.getText()
            + "\nNo HP: " + nomorhpField.getText()
            + "\nKota Tujuan: " + kotaCombo.getSelectedItem()
            + "\nKelas: " + kelas
            + "\nFasilitas: " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas))
            + "\nCatatan: " + catatanText.getText();

    JOptionPane.showMessageDialog(this, pesan, "Ringkasan Pemesanan Tiket", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tombolpesanButtonActionPerformed

    private void modegelapToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modegelapToggleActionPerformed
        boolean gelap = temaToggle.isSelected();
        if (gelap) {
            com.formdev.flatlaf.FlatDarkLaf.setup();
        } else {
            com.formdev.flatlaf.FlatLightLaf.setup();
        }
        com.formdev.flatlaf.FlatLaf.updateUI();
        temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");        // TODO add your handling code here:
    }//GEN-LAST:event_modegelapToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ekonomiButton;
    private javax.swing.JRadioButton eksekutifButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JToggleButton modegelapToggle;
    private javax.swing.JTextField namapemesananField;
    private javax.swing.JTextField nomorhpField;
    private javax.swing.JButton tombolpesanButton;
    // End of variables declaration//GEN-END:variables
}
